### ISSUE TITLE
Support amounts with cents

### ISSUE THREAD

**Issue by timonegk** [bit-bots/bitbots_drinks#4]
If we want to use this for the c.t., we should change the amount field to use cents instead of euros to reflect the prices there.

**Comment by timonegk** [comment]
Never mind, this is already supported (but I think the API is a bit strange)

**Comment by lilioid** [comment]
Yes it is supported by the API but not by the GUI.
I am reopening the issue because it is relevant to support this in the GUI as well if it is used in the CT.

**Comment by lilioid** [comment]
This has been implemented by now
